-- ============================================================================
-- SDG Thesis Classifier Database Schema (Oracle, idempotent)
-- Cal Poly Humboldt
-- Created: 2025-11-09
-- ============================================================================

-- =========================
-- Drop views if they exist
-- =========================
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_theses_with_sdgs';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_pending_with_sdgs';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_sdg_statistics';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- =========================
-- Drop tables if they exist
-- =========================
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN (
              'SDG_MAPPINGS','PENDING_THESES','THESES','AUDIT_LOG','AUTHORIZED_USERS','DEPARTMENTS'
            ))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =========================
-- Tables
-- =========================

-- Departments
CREATE TABLE departments (
  department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR2(100) NOT NULL UNIQUE,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Authorized users
CREATE TABLE authorized_users (
  user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(50)  NOT NULL UNIQUE,
  email         VARCHAR2(100) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  full_name     VARCHAR2(100),
  role          VARCHAR2(20)  DEFAULT 'reviewer'
                CHECK (role IN ('admin','reviewer','editor')),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  last_login    TIMESTAMP NULL,
  is_active     NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1))
);

-- Theses (approved)
CREATE TABLE theses (
  thesis_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR2(500) NOT NULL,
  author           VARCHAR2(200) NOT NULL,
  publication_date DATE NOT NULL,
  department_id    NUMBER NOT NULL,
  abstract         CLOB NOT NULL,
  url              VARCHAR2(500),
  discipline       VARCHAR2(100),
  keywords         CLOB,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
  approved_by      NUMBER,
  approved_at      TIMESTAMP NULL,
  CONSTRAINT fk_theses_dept       FOREIGN KEY (department_id) REFERENCES departments(department_id),
  CONSTRAINT fk_theses_approvedby FOREIGN KEY (approved_by)    REFERENCES authorized_users(user_id)
);

-- Auto-update UPDATED_AT on theses
CREATE OR REPLACE TRIGGER trg_theses_set_updated
BEFORE UPDATE ON theses
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Helpful single-column indexes
CREATE INDEX idx_theses_author     ON theses(author);
CREATE INDEX idx_theses_pubdate    ON theses(publication_date);
CREATE INDEX idx_theses_department ON theses(department_id);

-- Pending theses
CREATE TABLE pending_theses (
  pending_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           VARCHAR2(500) NOT NULL,
  author          VARCHAR2(200) NOT NULL,
  publication_date DATE NOT NULL,
  department_id   NUMBER NOT NULL,
  abstract        CLOB NOT NULL,
  url             VARCHAR2(500),
  discipline      VARCHAR2(100),
  keywords        CLOB,
  submitted_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  submitter_ip    VARCHAR2(45),
  submitter_email VARCHAR2(100),
  status          VARCHAR2(20) DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','needs_review')),
  reviewed_by     NUMBER NULL,
  reviewed_at     TIMESTAMP NULL,
  review_notes    CLOB,
  CONSTRAINT fk_pending_dept       FOREIGN KEY (department_id) REFERENCES departments(department_id),
  CONSTRAINT fk_pending_reviewedby FOREIGN KEY (reviewed_by)    REFERENCES authorized_users(user_id)
);

CREATE INDEX idx_pending_status     ON pending_theses(status);
CREATE INDEX idx_pending_submitted  ON pending_theses(submitted_at);
CREATE INDEX idx_pending_department ON pending_theses(department_id);

-- SDG mappings (many-to-many)
CREATE TABLE sdg_mappings (
  mapping_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thesis_id             NUMBER NULL,
  pending_id            NUMBER NULL,
  sdg_number            NUMBER NOT NULL CHECK (sdg_number BETWEEN 1 AND 16),
  confidence_score      NUMBER(5,4),
  ranking               NUMBER CHECK (ranking BETWEEN 1 AND 3),
  classification_method VARCHAR2(30) DEFAULT 'ai_auto'
                        CHECK (classification_method IN ('ai_auto','manual_edit','admin_override')),
  classified_at         TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT ck_mapping_oneof CHECK (
    (thesis_id  IS NOT NULL AND pending_id IS NULL) OR
    (thesis_id  IS NULL     AND pending_id IS NOT NULL)
  ),
  CONSTRAINT fk_mapping_thesis  FOREIGN KEY (thesis_id)  REFERENCES theses(thesis_id)      ON DELETE CASCADE,
  CONSTRAINT fk_mapping_pending FOREIGN KEY (pending_id) REFERENCES pending_theses(pending_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_sdg_thesis   ON sdg_mappings(thesis_id,  sdg_number);
CREATE UNIQUE INDEX uq_sdg_pending  ON sdg_mappings(pending_id, sdg_number);
CREATE INDEX idx_sdg_thesis_id      ON sdg_mappings(thesis_id);
CREATE INDEX idx_sdg_pending_id     ON sdg_mappings(pending_id);
CREATE INDEX idx_sdg_number         ON sdg_mappings(sdg_number);
CREATE INDEX idx_sdg_ranking        ON sdg_mappings(ranking);
CREATE INDEX idx_sdg_thesis_comp    ON sdg_mappings(sdg_number, thesis_id);

-- Audit log
CREATE TABLE audit_log (
  log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name     VARCHAR2(50) NOT NULL,
  record_id      NUMBER NOT NULL,
  action         VARCHAR2(20) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE','APPROVE','REJECT')),
  user_id        NUMBER,
  changed_fields CLOB,
  old_values     CLOB,
  new_values     CLOB,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES authorized_users(user_id)
);

CREATE INDEX idx_audit_table_record ON audit_log(table_name, record_id);
CREATE INDEX idx_audit_user         ON audit_log(user_id);
CREATE INDEX idx_audit_created      ON audit_log(created_at);

-- =========================
-- Seed data (idempotent)
-- =========================
MERGE INTO departments d
USING (SELECT 'Anthropology' AS name FROM dual UNION ALL
       SELECT 'Art' FROM dual UNION ALL
       SELECT 'Biology' FROM dual UNION ALL
       SELECT 'Business' FROM dual UNION ALL
       SELECT 'Chemistry' FROM dual UNION ALL
       SELECT 'Computer Science' FROM dual UNION ALL
       SELECT 'Economics' FROM dual UNION ALL
       SELECT 'Education' FROM dual UNION ALL
       SELECT 'Engineering' FROM dual UNION ALL
       SELECT 'English' FROM dual UNION ALL
       SELECT 'Environmental Science' FROM dual UNION ALL
       SELECT 'Geography' FROM dual UNION ALL
       SELECT 'Geology' FROM dual UNION ALL
       SELECT 'History' FROM dual UNION ALL
       SELECT 'Mathematics' FROM dual UNION ALL
       SELECT 'Music' FROM dual UNION ALL
       SELECT 'Philosophy' FROM dual UNION ALL
       SELECT 'Physics' FROM dual UNION ALL
       SELECT 'Political Science' FROM dual UNION ALL
       SELECT 'Psychology' FROM dual UNION ALL
       SELECT 'Sociology' FROM dual UNION ALL
       SELECT 'Theatre Arts' FROM dual UNION ALL
       SELECT 'Wildlife' FROM dual UNION ALL
       SELECT 'Other' FROM dual) src
ON (d.department_name = src.name)
WHEN NOT MATCHED THEN
  INSERT (department_name) VALUES (src.name);

MERGE INTO authorized_users u
USING (SELECT 'admin' AS username,
              'admin@humboldt.edu' AS email,
              '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' AS pwd,
              'System Administrator' AS full_name,
              'admin' AS role
       FROM dual) src
ON (u.username = src.username OR u.email = src.email)
WHEN NOT MATCHED THEN
  INSERT (username, email, password_hash, full_name, role)
  VALUES (src.username, src.email, src.pwd, src.full_name, src.role);

-- =========================
-- Views (CLOB-safe)
-- =========================

-- Approved theses with SDGs (CLOBs trimmed to 4000 for display)
CREATE OR REPLACE VIEW v_theses_with_sdgs AS
SELECT
  t.thesis_id,
  t.title,
  t.author,
  t.publication_date,
  d.department_name,
  DBMS_LOB.SUBSTR(t.abstract, 4000)   AS abstract,
  t.url,
  t.discipline,
  DBMS_LOB.SUBSTR(t.keywords, 4000)   AS keywords,
  (SELECT LISTAGG('SDG ' || sm.sdg_number || ' (' || TO_CHAR(ROUND(sm.confidence_score*100,1)) || '%)', ', ')
           WITHIN GROUP (ORDER BY sm.ranking)
     FROM sdg_mappings sm
     WHERE sm.thesis_id = t.thesis_id) AS sdg_classifications,
  (SELECT LISTAGG(TO_CHAR(sm2.sdg_number), ',')
           WITHIN GROUP (ORDER BY sm2.ranking)
     FROM sdg_mappings sm2
     WHERE sm2.thesis_id = t.thesis_id) AS sdg_numbers,
  t.created_at,
  t.approved_at,
  au.full_name AS approved_by_name
FROM theses t
LEFT JOIN departments      d  ON d.department_id = t.department_id
LEFT JOIN authorized_users au ON au.user_id      = t.approved_by;
/

-- Pending theses with SDGs (CLOBs trimmed to 4000 for display)
CREATE OR REPLACE VIEW v_pending_with_sdgs AS
SELECT
  pt.pending_id,
  pt.title,
  pt.author,
  pt.publication_date,
  d.department_name,
  DBMS_LOB.SUBSTR(pt.abstract, 4000)  AS abstract,
  pt.url,
  pt.discipline,
  DBMS_LOB.SUBSTR(pt.keywords, 4000)  AS keywords,
  (SELECT LISTAGG('SDG ' || sm.sdg_number || ' (' || TO_CHAR(ROUND(sm.confidence_score*100,1)) || '%)', ', ')
           WITHIN GROUP (ORDER BY sm.ranking)
     FROM sdg_mappings sm
     WHERE sm.pending_id = pt.pending_id) AS sdg_classifications,
  (SELECT LISTAGG(TO_CHAR(sm2.sdg_number), ',')
           WITHIN GROUP (ORDER BY sm2.ranking)
     FROM sdg_mappings sm2
     WHERE sm2.pending_id = pt.pending_id) AS sdg_numbers,
  pt.status,
  pt.submitted_at,
  pt.submitter_email
FROM pending_theses pt
LEFT JOIN departments d ON d.department_id = pt.department_id;
/

-- SDG distribution stats (approved only)
CREATE OR REPLACE VIEW v_sdg_statistics AS
SELECT
  sm.sdg_number,
  CASE sm.sdg_number
    WHEN 1  THEN 'No Poverty'
    WHEN 2  THEN 'Zero Hunger'
    WHEN 3  THEN 'Good Health and Well-being'
    WHEN 4  THEN 'Quality Education'
    WHEN 5  THEN 'Gender Equality'
    WHEN 6  THEN 'Clean Water and Sanitation'
    WHEN 7  THEN 'Affordable and Clean Energy'
    WHEN 8  THEN 'Decent Work and Economic Growth'
    WHEN 9  THEN 'Industry, Innovation and Infrastructure'
    WHEN 10 THEN 'Reduced Inequalities'
    WHEN 11 THEN 'Sustainable Cities and Communities'
    WHEN 12 THEN 'Responsible Consumption and Production'
    WHEN 13 THEN 'Climate Action'
    WHEN 14 THEN 'Life Below Water'
    WHEN 15 THEN 'Life on Land'
    WHEN 16 THEN 'Peace, Justice and Strong Institutions'
  END AS sdg_name,
  COUNT(DISTINCT sm.thesis_id) AS thesis_count,
  ROUND(AVG(sm.confidence_score) * 100, 2) AS avg_confidence
FROM sdg_mappings sm
WHERE sm.thesis_id IS NOT NULL
GROUP BY sm.sdg_number
ORDER BY sm.sdg_number;
/

-- =========================
-- Procedure: approve pending thesis
-- =========================
CREATE OR REPLACE PROCEDURE sp_approve_pending_thesis(
  p_pending_id    IN  NUMBER,
  p_user_id       IN  NUMBER,
  p_new_thesis_id OUT NUMBER
) AS
  v_title         theses.title%TYPE;
  v_author        theses.author%TYPE;
  v_pub_date      theses.publication_date%TYPE;
  v_department_id theses.department_id%TYPE;
  v_abstract      theses.abstract%TYPE;
  v_url           theses.url%TYPE;
  v_discipline    theses.discipline%TYPE;
  v_keywords      theses.keywords%TYPE;
BEGIN
  -- lock the pending row to move
  SELECT title, author, publication_date, department_id, abstract,
         url, discipline, keywords
  INTO   v_title, v_author, v_pub_date, v_department_id, v_abstract,
         v_url, v_discipline, v_keywords
  FROM pending_theses
  WHERE pending_id = p_pending_id
  FOR UPDATE;

  INSERT INTO theses (
    title, author, publication_date, department_id, abstract,
    url, discipline, keywords, approved_by, approved_at
  ) VALUES (
    v_title, v_author, v_pub_date, v_department_id, v_abstract,
    v_url, v_discipline, v_keywords, p_user_id, SYSTIMESTAMP
  )
  RETURNING thesis_id INTO p_new_thesis_id;

  INSERT INTO sdg_mappings (thesis_id, sdg_number, confidence_score, ranking, classification_method)
  SELECT p_new_thesis_id, sdg_number, confidence_score, ranking, classification_method
  FROM sdg_mappings
  WHERE pending_id = p_pending_id;

  UPDATE pending_theses
  SET status = 'approved',
      reviewed_by = p_user_id,
      reviewed_at = SYSTIMESTAMP
  WHERE pending_id = p_pending_id;

  INSERT INTO audit_log (table_name, record_id, action, user_id)
  VALUES ('theses', p_new_thesis_id, 'APPROVE', p_user_id);
END;
/

